#!/bin/bash

gcc -o out1 hw02.c
gcc -o out2 hw02_after_hint.c
gcc -o data data.c

for (( i=1; i<=10000; i=i+1 )); do
    ./data > in
	./out1 < in > result1
	./out2 < in > result2
	diff result1 result2 > /dev/null
	ans=$?
	if [ "$ans" = "1" ]; then
		echo -e "diff\n"
		cat in
		break
	fi
done
